server:
    port: 8088
spring:
    application:
        name: user-service
    datasource:
        username: isa_user
        password: isa_password
        url: jdbc:postgresql://localhost:5432/userService
    jpa:
      hibernate:
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.xml
jwt:
    expiration-time: 300000000
    SECRET: megasecretkey